---
- src: dunn.tz
  version: '1'

- src: zzet.rbenv
  version: '3.1.1'

- src: dunn.acme-nginx-passenger
  version: '2'

- src: geerlingguy.postgresql
  version: '1.0.2'

- src: dunn.security
  version: '2'
