---
- name: Provision a RHEL/CentOS server for Mastodon
  remote_user: root
  hosts: all

  vars_prompt:
    - name: keyfile
      default: ~/.ssh/id_rsa.pub
      prompt: Path to SSH public key for deploying
      private: no

    - name: deploy_pass
      confirm: yes
      encrypt: sha512_crypt
      private: yes
      prompt: Password for mastodon user
      salt_size: 7

    - name: smtp_server
      default: smtp.sparkpostmail.com
      prompt: SMTP server
      private: no

    - name: smtp_login
      default: SMTP_Injection
      prompt: SMTP server login
      private: no

    - name: smtp_pass
      prompt: SMTP server password or API key
      private: yes

    - name: smtp_from
      prompt: “From:” address for SMTP server
      private: no

  vars:
    deploy_user: mastodon

    pg_user: mastodon
    pg_db: mastodon

    postgresql_databases:
      - name: "{{ pg_db }}"
    postgresql_users:
      - name: "{{ pg_user }}"
        db: "{{ pg_db }}"

    rbenv:
      env: user
      version: v1.1.0
      default_ruby: 2.3.3
      rubies:
        - version: 2.3.3

  roles:
    - role: dunn.tz
    # this user is used by the rbenv role below
    - role: nginx-deploy-user
    - role: fixme_bzip2
    - role: zzet.rbenv
      rbenv_users:
        - "{{ deploy_user }}"
    - role: geerlingguy.postgresql
    - role: mastodon
    - role: dunn.security
