---
- name: add full Nginx configuration
  template:
    src: app.conf.j2
    dest: /etc/nginx/conf.d/app.conf
    force: yes

- name: ensure {{ app_dir }} exists
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: nginx

- name: restart Nginx
  systemd:
    enabled: yes
    name: nginx
    state: restarted

- name: schedule Nginx to restart after certificate renewal
  cron:
    job: "systemctl restart nginx"
    name: restart Nginx
    special_time: monthly
    user: root

- name: make sure SELinux doesn\'t block Puma and Node
  command: semanage port -a -t http_port_t -p tcp {{ item }}
  with_items:
    - 3000
    - 4000
