---
- name: add EPEL repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

- name: update all yum packages
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: install dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - curl-devel
    - git
    - nginx
    - openssl-devel
    # for acme-tiny
    - python34-devel

- name: remove app.conf
  file:
    path: /etc/nginx/conf.d/app.conf
    state: absent

- name: start Nginx
  systemd:
    name: nginx
    state: started

- name: clone acme-tiny repository
  git:
    repo: https://github.com/diafygi/acme-tiny.git
    dest: /home/{{ deploy_user }}/acme-tiny
    # This is the latest commit; update as necessary
    version: daba51d37efd7c1f205f9da383b9b09968e30d29
  become: true
  become_user: "{{ deploy_user }}"
