---
- name: create “{{ deploy_group }}” group
  group:
    name: "{{ deploy_group }}"

- name: create “{{ deploy_user }}” user
  user:
    generate_ssh_key: yes
    groups: "{{ deploy_group }},wheel"
    home: /home/{{ deploy_user }}
    name: "{{ deploy_user }}"
    password: "{{ deploy_pass }}"
    ssh_key_bits: 4096
    update_password: on_create

- name: add key to deploy user’s authorized_keys
  authorized_key:
    key: "{{ lookup('file', keyfile) }}"
    user: "{{ deploy_user }}"
