---
# See https://github.com/zzet/ansible-rbenv-role/issues/12
- name: install bundler
  gem:
    executable: /home/{{ deploy_user }}/.rbenv/shims/gem
    name: bundler
    state: latest
  become: yes
  become_user: "{{ deploy_user }}"
