---
- name: enable firewalld
  systemd:
    enabled: yes
    name: firewalld
    state: started

# https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Security_Guide/sec-Using_Firewalls.html
- name: add services to firewalld allowed protocols
  command: firewall-cmd --add-service={{ item }} --permanent --zone=public
  with_items:
    - http
    - https

- name: reload firewalld
  command: firewall-cmd --reload
