---
# https://github.com/tootsuite/mastodon/blob/master/docs/Running-Mastodon/Production-guide.md#cronjobs
- name: set up cron jobs
  cron:
    job: "{{ item.job }}"
    name: "{{ item.name }}"
    special_time: daily
    user: "{{ deploy_user }}"
  with_items:
    - name: "mastodon:daily"
      job: "RAILS_ENV=production /bin/bash -lc 'cd {{ app_dir }}/current && bundle exec rake mastodon:daily'"
