---
- name: add EPEL repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

- name: download NodeSource repo
  get_url:
    url: https://rpm.nodesource.com/pub_6.x/el/7/x86_64/nodejs-{{ node_ver }}-1nodesource.el7.centos.x86_64.rpm
    checksum: sha256:{{ node_sha }}
    dest: /tmp/nodejs-devel-{{ node_ver }}-1nodesource.el7.centos.x86_64.rpm

- name: install NodeSource repo
  yum:
    name: /tmp/nodejs-devel-{{ node_ver }}-1nodesource.el7.centos.x86_64.rpm

- name: update all yum packages
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: install dependencies
  yum:
    name: "{{ item }}"
  with_items:
    - ImageMagick
    - binutils
    - curl-devel
    # to compile unf_ext
    - gcc-c++
    - git
    # to compile nokogiri extensions
    - libxml2-devel
    - libxslt-devel
    - nginx
    - nodejs
    - openssl-devel
    # to compile pg extensions
    - postgresql-devel
    # for acme-tiny
    - python34-devel
    - redis
    - xz

- name:  start redis
  systemd:
    enabled: true
    name: redis
    state: started

- name: install yarn
  npm:
    global: yes
    name: yarn
    state: latest
