---
# https://letsencrypt.org/how-it-works/
# https://github.com/diafygi/acme-tiny#how-to-use-this-script
# https://github.com/diafygi/letsencrypt-nosudo#how-to-use-the-signing-script
- name: remove mastodon.conf
  file:
    path: /etc/nginx/conf.d/mastodon.conf
    state: absent

- name: start Nginx
  systemd:
    name: nginx
    state: started

- name: clone acme-tiny repository
  git:
    repo: https://github.com/diafygi/acme-tiny.git
    dest: /home/{{ deploy_user }}/acme-tiny
    # This is the latest commit; update as necessary
    version: daba51d37efd7c1f205f9da383b9b09968e30d29
  become: true
  become_user: "{{ deploy_user }}"

- name: create ACME directories
  file:
    group: "{{ deploy_group }}"
    owner: "{{ deploy_user }}"
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/{{ deploy_user }}/acme
    - /usr/share/nginx/html/.well-known/acme-challenge

- name: generate TLS user private key
  command: openssl genrsa 4096
  register: tls_user

- name: write TLS user private key
  copy:
    content: "{{ tls_user.stdout }}"
    dest: /home/{{ deploy_user }}/acme/user.key
    force: yes
    group: "{{ deploy_group }}"
    owner: "{{ deploy_user }}"

- name: generate TLS domain private key
  command: openssl genrsa 4096
  register: tls_domain

- name: write TLS domain private key
  copy:
    content: "{{ tls_domain.stdout }}"
    dest: /etc/ssl/certs/{{ ansible_ssh_host }}.key
    force: yes
    group: "{{ deploy_group }}"
    owner: "{{ deploy_user }}"

- name: copy default OpenSSL config
  copy:
    dest: /home/{{ deploy_user }}/acme/{{ ansible_ssh_host }}.cnf
    group: "{{ deploy_group }}"
    owner: "{{ deploy_user }}"
    remote_src: yes
    src: /etc/pki/tls/openssl.cnf

- name: add DNS info to local config
  lineinfile:
    dest: /home/{{ deploy_user }}/acme/{{ ansible_ssh_host }}.cnf
    line: "[SAN]\nsubjectAltName=DNS:{{ ansible_ssh_host }},DNS:www.{{ ansible_ssh_host }}"
  become: true
  become_user: "{{ deploy_user }}"

- name: generate Certificate Signing Request
  command: openssl req -new -sha256 \
                       -key /etc/ssl/certs/{{ ansible_ssh_host }}.key \
                       -subj "/" -reqexts SAN \
                       -config /home/{{ deploy_user }}/acme/{{ ansible_ssh_host }}.cnf
  register: csr

- name: write Certificate Signing Request
  copy:
    content: "{{ csr.stdout }}"
    dest: /home/{{ deploy_user }}/acme/{{ ansible_ssh_host }}.csr
    force: yes
    group: "{{ deploy_group }}"
    owner: "{{ deploy_user }}"

- name: generate TLS certificate
  command: python3 /home/{{ deploy_user }}/acme-tiny/acme_tiny.py \
                   --account-key /home/{{ deploy_user }}/acme/user.key \
                   --csr /home/{{ deploy_user }}/acme/{{ ansible_ssh_host }}.csr \
                   --acme-dir /usr/share/nginx/html/.well-known/acme-challenge
  register: cert

- name: write TLS certificate
  copy:
    content: "{{ cert.stdout }}"
    dest: /home/{{ deploy_user }}/acme/{{ ansible_ssh_host }}.crt
    force: yes
    group: "{{ deploy_group }}"
    owner: "{{ deploy_user }}"

# This is an intermediate certificate; it's not strictly required but
# not having it will cap your Qualys ranking at B
- name: download Let’s Encrypt X3 certificate
  get_url:
    url: https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem
    checksum: sha256:{{ intermediate_cert_sha }}
    dest: /etc/ssl/certs/lets-encrypt-x3-cross-signed.pem
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"

- name: combine domain and intermediate certificates
  command: cat /home/{{ deploy_user }}/acme/{{ ansible_ssh_host }}.crt \
               /etc/ssl/certs/lets-encrypt-x3-cross-signed.pem \
  register: combined_cert

- name: write combined cert
  copy:
    content: "{{ combined_cert.stdout }}"
    dest: /etc/ssl/certs/{{ ansible_ssh_host }}.pem
    force: yes
    group: "{{ deploy_group }}"
    owner: "{{ deploy_user }}"

- name: ensure /home/{{ deploy_user }}/bin exists
  file:
    state: directory
    path: /home/{{ deploy_user }}/bin
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"

- name: install renew.sh script
  template:
    src: renew.sh.j2
    dest: /home/{{ deploy_user }}/bin/renew.sh
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: 0755

- name: schedule certificate renewal
  cron:
    name: "ACME renewal"
    special_time: monthly
    job: /home/{{ deploy_user }}/bin/renew.sh \
         2>> /var/log/acme_error.log
    cron_file: acme_renewal
    user: "{{ deploy_user }}"

- name: make ACME log writeable by {{ deploy_user }}
  file:
    path: /var/log/acme_error.log
    state: touch
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
