---
- name: install bundler
  gem:
    executable: /home/{{ deploy_user }}/.rbenv/shims/gem
    name: bundler
    state: latest
  become: yes
  become_user: "{{ deploy_user }}"

- name: set bundler_path
  set_fact:
    bundler_path: /home/{{ deploy_user }}/.rbenv/shims/bundle
