---
- name: install bundler
  gem:
    name: bundler
    state: latest
    user_install: no

- name: get bundler path
  command: which bundle
  register: which_bundle

- name: set bundler_path
  set_fact:
    bundler_path: "{{ which_bundle.stdout }}"
