---
- name: install Mastodon services
  template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/system/{{ item }}
    mode: 0600
    owner: root
    group: root
  with_items:
    - mastodon-sidekiq.service
    - mastodon-streaming.service
    - mastodon-web.service

- name: start Mastodon services
  systemd:
    daemon_reload: true
    enabled: true
    name: "{{ item }}"
    state: started
  with_items:
    - mastodon-sidekiq
    - mastodon-streaming
    - mastodon-web
